### ISSUE TITLE
... always like your fast tagger

### ISSUE THREAD

**Issue by kalle07** [starik222/BooruDatasetTagManager#220]
req txt update already done ... btu ...

(boorutager) d:\kohya_ss_Booru\AiApiServer>python --version
Python 3.12.9

(boorutager) d:\kohya_ss_Booru\AiApiServer>python main.py
Have CUDA:  True
CUDA Count:  1
Using interrogator device: cuda
Traceback (most recent call last):
  File "d:\kohya_ss_Booru\AiApiServer\main.py", line 20, in <module>
    import models
  File "d:\kohya_ss_Booru\AiApiServer\models.py", line 10, in <module>
    from modules import (
  File "d:\kohya_ss_Booru\AiApiServer\modules\captioning.py", line 4, in <module>
    from .interrogators import BLIPLargeCaptioning, BLIP2Captioning, GITLargeCaptioning, Florence2Captioning, \
ImportError: cannot import name 'Qwen3CaptionCaptioning' from 'modules.interrogators' (d:\kohya_ss_Booru\AiApiServer\modules\interrogators\__init__.py). Did you mean: 'Qwen25CaptionCaptioning'?

**Comment by kalle07** [comment]
the server runs  but 
BooruDatasetTagManager.exe
now version warning 2.6.0
and dont run, it pop up an error if yi wnat choose the tagger model  . . .   ;)

**Comment by kalle07** [comment]
hmmm. dont know what it is ? 
server runs...
i start BooruDatasetTagManager.exe, it pop up if i want setup tagger 

<img width="1103" height="639" alt="Image" src="https://github.com/user-attachments/assets/b0f03c3f-0877-4baa-8c01-3a876a9eff34" />

**Comment by starik222** [comment]
"If you receive an error when opening the Autotagger settings form, delete the ColorScheme.json file from the program folder and restart the program." [2.5.2](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.5.2)

**Comment by starik222** [comment]
As I wrote in the readme, Florence2 only works with transformers=4.49.0, and I can't do anything about it because it's a model-specific issue. Microsoft needs to update their models for everything to work.
As for gguf... that's why I implemented OpenAI support. Most AI software solutions now support this exchange format, and they perform much better than AiApiServer, supporting most models. So, from now on, I'll be supporting AiApiServer as little as possible, as it doesn't really make sense right now, except maybe for the WD Tagger.
